import {Geist, Geist_Mono} from "next/font/google";
import "@/app/style/globals.css";
import {ThemeProvider} from "@/components/front-UI/theme/theme-provider";
import AppNavbar from "@/components/front-UI/nav-layout/app-navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-linear-to-b from-slate-950 via-slate-900 to-slate-950 text-slate-100`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <AppNavbar>
                {children}
            </AppNavbar>
        </ThemeProvider>
        </body>
        </html>
    );
}
